version: "3.9"
services:
  portal:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: production
      SECRET_KEY: "sua_chave_secreta_aqui"  # Substitua por uma chave segura
    restart: always
