plano = {
    "meses": {
        "Mês 1": [
            {"dia": 1,"capitulos": "Mt 1-2"},
            {"dia": 2,"capitulos": "Mt 3-4"},
            {"dia": 3,"capitulos": "Mt 5"},
            { "dia": 4,"capitulos": "Mt 6"},
            {"dia": 5,"capitulos": "Mt 7"},
            {"dia": 6,"capitulos": "Mt 8"},
            {"dia": 7,"capitulos": "Mt 9"},
            {"dia": 8,"capitulos": "Mt 10"},
            {"dia": 9,"capitulos": "Mt 11"},
            {"dia": 10,"capitulos": "Mt 12"},
            {"dia": 11,"capitulos": "Mt 13"},
            {"dia": 12,"capitulos": "Mt 14"},
            {"dia": 13,"capitulos": "Mt 15"},
            {"dia": 14,"capitulos": "Mt 16-17"},
            {"dia": 15,"capitulos": "Mt 18"},
            {"dia": 16,"capitulos": "Mt 19"},
            {"dia": 17,"capitulos": "Mt 20"},
            {"dia": 18,"capitulos": "Mt 21"},
            {"dia": 19,"capitulos": "Mt 22"},
            {"dia": 20,"capitulos": "Mt 23"},
            {"dia": 21,"capitulos": "Mt 24"},
            {"dia": 22,"capitulos": "Mt 25"},
            {"dia": 23,"capitulos": "Mt 26"},
            {"dia": 24,"capitulos": "Mt 27"},
            {"dia": 25,"capitulos": "Mt 28"},
            {"dia": 26,"capitulos": "Mc 1-2"},
            {"dia": 27,"capitulos": "Mc 3"},
            {"dia": 28,"capitulos": "Mc 4"},
            {"dia": 29,"capitulos": "Mc 5"},
            {"dia": 30,"capitulos": "Mc 6"},
        ],
        "Mês 2": [
            {"dia": 1,"capitulos": "Mc 8"},
            {"dia": 2,"capitulos": "Mc 9"},
            {"dia": 3,"capitulos": "Mc 10"},
            {"dia": 4,"capitulos": "Mc 11"},
            {"dia": 5,"capitulos": "Mc 12"},
            {"dia": 6,"capitulos": "Mc 13"},
            {"dia": 7,"capitulos": "Mc 14"},
            {"dia": 8,"capitulos": "Mc 15"},
            {"dia": 9,"capitulos": "Mc 16"},
            {"dia": 10,"capitulos": "Lc 1"},
            {"dia": 11,"capitulos": "Lc 2"},
            {"dia": 12,"capitulos": "Lc 3"},
            {"dia": 13,"capitulos": "Lc 4"},
            {"dia": 14,"capitulos": "Lc 5"},
            {"dia": 15,"capitulos": "Lc 6"},
            {"dia": 16,"capitulos": "Lc 7"},
            {"dia": 17,"capitulos": "Lc 8"},
            {"dia": 18,"capitulos": "Lc 9"},
            {"dia": 19,"capitulos": "Lc 10"},
            {"dia": 20,"capitulos": "Lc 11"},
            {"dia": 21,"capitulos": "Lc 12"},
            {"dia": 22,"capitulos": "Lc 13"},
            {"dia": 23,"capitulos": "Lc 14"},
            {"dia": 24,"capitulos": "Lc 15"},
            {"dia": 25,"capitulos": "Lc 16"},
            {"dia": 26,"capitulos": "Lc 17"},
            {"dia": 27,"capitulos": "Lc 18"},
            {"dia": 28,"capitulos": "Lc 19"},
        ],
        "Mês 3": [
            {"dia": 1,"capitulos": "Lc 20"},
            {"dia": 2,"capitulos": "Lc 21"},
            {"dia": 3,"capitulos": "Lc 22"},
            {"dia": 4,"capitulos": "Lc 23"},
            {"dia": 5,"capitulos": "Lc 24"},
            {"dia": 6,"capitulos": "Jo 1"},
            {"dia": 7,"capitulos": "Jo 2"},
            {"dia": 8,"capitulos": "Jo 3"},
            {"dia": 9,"capitulos": "Jo 4"},
            {"dia": 10,"capitulos": "Jo 5"},
            {"dia": 11,"capitulos": "Jo 6"},
            {"dia": 12,"capitulos": "Jo 7"},
            {"dia": 13,"capitulos": "Jo 8"},
            {"dia": 14,"capitulos": "Jo 9"},
            {"dia": 15,"capitulos": "Jo 10"},
            {"dia": 16,"capitulos": "Jo 11"},
            {"dia": 17,"capitulos": "Jo 12"},
            {"dia": 18,"capitulos": "Jo 13"},
            {"dia": 19,"capitulos": "Jo 14"},
            {"dia": 20,"capitulos": "Jo 15"},
            {"dia": 21,"capitulos": "Jo 16"},
            {"dia": 22,"capitulos": "Jo 17"},
            {"dia": 23,"capitulos": "Jo 18"},
            {"dia": 24,"capitulos": "Jo 19"},
            {"dia": 25,"capitulos": "Jo 20-21"},
            {"dia": 26,"capitulos": "At 1"},
            {"dia": 27,"capitulos": "At 2"},
            {"dia": 28,"capitulos": "At 3"},
            {"dia": 29,"capitulos": "At 4"},
            {"dia": 30,"capitulos": "At 5"},
            {"dia": 30,"capitulos": "At 6"},
        ],
        "Mês 4": [
            {"dia": 1,"capitulos": "At 7"},
            {"dia": 2,"capitulos": "At 8"},
            {"dia": 3,"capitulos": "At 9"},
            {"dia": 4,"capitulos": "At 10"},
            {"dia": 5,"capitulos": "At 11"},
            {"dia": 6,"capitulos": "At 12"},
            {"dia": 7,"capitulos": "At 13"},
            {"dia": 8,"capitulos": "At 14"},
            {"dia": 9,"capitulos": "At 15"},
            {"dia": 10,"capitulos": "At 16"},
            {"dia": 11,"capitulos": "At 17"},
            {"dia": 12,"capitulos": "At 18"},
            {"dia": 13,"capitulos": "At 19"},
            {"dia": 14,"capitulos": "At 20"},
            {"dia": 15,"capitulos": "At 21"},
            {"dia": 16,"capitulos": "At 22"},
            {"dia": 17,"capitulos": "At 23"},
            {"dia": 18,"capitulos": "At 24-25"},
            {"dia": 19,"capitulos": "At 26"},
            {"dia": 20,"capitulos": "At 27"},
            {"dia": 21,"capitulos": "At 28"},
            {"dia": 22,"capitulos": "Rm 1"},
            {"dia": 23,"capitulos": "Rm 2"},
            {"dia": 24,"capitulos": "Rm 3-4"},
            {"dia": 25,"capitulos": "Rm 5-6"},
            {"dia": 26,"capitulos": "Rm 7"},
            {"dia": 27,"capitulos": "Rm 8"},
            {"dia": 28,"capitulos": "Rm 9-10"},
            {"dia": 29,"capitulos": "Rm 11"},
            {"dia": 30,"capitulos": "Rm 12-13"}
        ],
        "Mês 5": [
            {"dia": 1,"capitulos": "Rm 14-16"},
            {"dia": 2,"capitulos": "1Co 1"},
            {"dia": 3,"capitulos": "1Co 2-3"},
            {"dia": 4,"capitulos": "1Co 4-5"},
            {"dia": 5,"capitulos": "1Co 6-7"},
            {"dia": 6,"capitulos": "1Co 8-9"},
            {"dia": 7,"capitulos": "1Co 10"},
            {"dia": 8,"capitulos": "1Co 11"},
            {"dia": 9,"capitulos": "1Co 12-13"},
            {"dia": 10,"capitulos": "1Co 14"},
            {"dia": 11,"capitulos": "1Co 15-16"},
            {"dia": 12,"capitulos": "2Co 1-2"},
            {"dia": 13,"capitulos": "2Co 3-4"},
            {"dia": 14,"capitulos": "2Co 5-6"},
            {"dia": 15,"capitulos": "2Co 7-8"},
            {"dia": 16,"capitulos": "2Co 9-10"},
            {"dia": 17,"capitulos": "2Co 11-13"},
            {"dia": 18,"capitulos": "Gl 1-2"},
            {"dia": 19,"capitulos": "Gl 3-4"},
            {"dia": 20,"capitulos": "Gl 5-6"},
            {"dia": 21,"capitulos": "Ef 1-2"},
            {"dia": 22,"capitulos": "Ef 3-4"},
            {"dia": 23,"capitulos": "Ef 5-6"},
            {"dia": 24,"capitulos": "Fp 1-2"},
            {"dia": 25,"capitulos": "Fp 3-4"},
            {"dia": 26,"capitulos": "Cl 1-2"},
            {"dia": 27,"capitulos": "Cl 3-4"},
            {"dia": 28,"capitulos": "1Ts 1-2"},
            {"dia": 29,"capitulos": "1Ts 3-4"},
            {"dia": 30,"capitulos": "1Ts 5"},
            {"dia": 31,"capitulos": "2 Ts"}
        ],
        "Mês 6": [
            {"dia": 1,"capitulos": "1Tm 1-2"},
            {"dia": 2,"capitulos": "1Tm 3-4"},
            {"dia": 3,"capitulos": "1Tm 5-6"},
            {"dia": 4,"capitulos": "2Tm 1-1"},
            {"dia": 5,"capitulos": "2Tm 3-4"},
            {"dia": 6,"capitulos": "Tt"},
            {"dia": 7,"capitulos": "Fm"},
            {"dia": 8,"capitulos": "Hb 1-3"},
            {"dia": 9,"capitulos": "Hb 4-6"},
            {"dia": 10,"capitulos": "Hb 7-8"},
            {"dia": 11,"capitulos": "Hb 9"},
            {"dia": 12,"capitulos": "Hb 10"},
            {"dia": 13,"capitulos": "Hb 11"},
            {"dia": 14,"capitulos": "Hb 12-13"},
            {"dia": 15,"capitulos": "Tg 1-2"},
            {"dia": 16,"capitulos": "Tg 3-5"},
            {"dia": 17,"capitulos": "1Pe 1-2"},
            {"dia": 18,"capitulos": "1Pe 3-5"},
            {"dia": 19,"capitulos": "2Pe"},
            {"dia": 20,"capitulos": "1Jo 1-3"},
            {"dia": 21,"capitulos": "1Jo 4-5"},
            {"dia": 22,"capitulos": "2Jo - 3Jo - Jd"},
            {"dia": 23,"capitulos": "Ap 1-3"},
            {"dia": 24,"capitulos": "Ap 4-6"},
            {"dia": 25,"capitulos": "Ap 7-9"},
            {"dia": 26,"capitulos": "Ap 10-12"},
            {"dia": 27,"capitulos": "Ap 13-15"},
            {"dia": 28,"capitulos": "Ap 16-17"},
            {"dia": 28,"capitulos": "Ap 18-20"},
            {"dia": 28,"capitulos": "Ap 21-22"},
        ]
    }
}